import { PageType } from '../types';
import PresentationProjects from '../components/PresentationProjects';
import { SERVICES_DATA } from '../data/tasblockData';
export default function HomePage({onNavigate}:{onNavigate:(page:PageType)=>void}) {
 return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-16 space-y-16">
  <section className="grid lg:grid-cols-2 gap-8 items-center"><div className="space-y-6"><p className="text-sm font-semibold text-[#99D5D9]">SISTEM BINAAN KOMPOSIT TASBLOCK</p><h1 className="text-4xl sm:text-5xl font-bold text-white leading-tight">Kenali sistem.<br/>Bayangkan projek anda.</h1><p className="text-lg text-slate-300 leading-relaxed">Panel, adaptor dan sambungan yang membentuk satu sistem binaan. Tasblock Builder membantu pelanggan individu dan kontraktor tempatan meneroka pilihan untuk projek mereka.</p><div className="flex flex-wrap gap-3"><button onClick={()=>onNavigate('products')} className="min-h-12 rounded-xl bg-[#99D5D9] px-5 py-3 font-bold text-[#071827]">Kenali sistem Tasblock →</button><button onClick={()=>onNavigate('enquiry')} className="min-h-12 rounded-xl border border-slate-600 px-5 py-3 text-white">Bincang projek anda</button></div></div><div className="relative min-w-0 pb-14 sm:pb-20 lg:ml-4"><div className="relative aspect-[6/5]"><figure className="absolute inset-y-0 left-[5%] right-0 overflow-hidden rounded-3xl"><img src="/images/hero.webp" width="1440" height="960" alt="Rumah tropika dengan beranda dan taman" className="absolute inset-y-0 right-0 h-full w-[105.263%] max-w-none object-cover object-right" fetchPriority="high"/></figure></div><figure className="absolute bottom-0 left-0 sm:-left-4 w-[60%] sm:w-[58%] max-w-sm rounded-2xl overflow-hidden shadow-2xl"><img src="/images/tasblock/assembly-hero-ribbed-v2.png" width="1536" height="1024" alt="Ilustrasi AI dua pekerja memasang panel komposit pada struktur dinding" className="w-full aspect-[3/2] object-cover"/></figure></div></section>
  <section aria-labelledby="start-title" className="space-y-5"><h2 id="start-title" className="text-2xl font-bold text-white">Apa yang anda ingin tahu?</h2><div className="grid md:grid-cols-3 gap-5">{[
   ['products','01','Bagaimana sistem ini berfungsi?','Kenali komponen, bahan, pemasangan dan penggunaan semula.'],
   ['projects','02','Di mana ia pernah digunakan?','Lihat rumah, sekolah, asrama dan aplikasi dalam rekod pengeluar.'],
   ['services','03','Bagaimana saya boleh bermula?','Pilih reka & bina, bekalan komponen, bekal & pasang atau latihan.'],
  ].map(([page,num,title,text])=><button key={page} onClick={()=>onNavigate(page as PageType)} className="text-left rounded-2xl border border-slate-700 bg-slate-900/60 p-6 space-y-4 hover:border-[#99D5D9] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#99D5D9]"><span className="text-[#99D5D9] text-sm">{num}</span><h3 className="text-xl font-bold text-white">{title}</h3><p className="text-slate-300">{text}</p><span className="block text-[#99D5D9]">Terokai →</span></button>)}</div></section>
  <PresentationProjects featured />
  <section className="space-y-5"><h2 className="text-2xl font-bold text-white">Bantuan untuk langkah seterusnya</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{SERVICES_DATA.map(service=><a key={service.id} href={`#services?service=${service.id}`} className="rounded-2xl border border-slate-700 p-5 space-y-3 hover:bg-slate-900"><h3 className="text-lg font-bold text-[#99D5D9]">{service.title}</h3><p className="text-base text-slate-300">{service.shortDesc}</p></a>)}</div></section>
  <section className="rounded-3xl bg-[#12314a] p-6 sm:p-10 flex flex-col md:flex-row gap-6 md:items-center md:justify-between"><div className="space-y-3 max-w-2xl"><h2 className="text-2xl font-bold text-white">Teknologi pengeluar. Sokongan tempatan.</h2><p className="text-slate-300">Teknologi dan rujukan projek berasal daripada Tasblock (M) Sdn. Bhd. Tasblock Builder ialah inisiatif berasingan untuk keperluan pelanggan tempatan.</p></div><button onClick={()=>onNavigate('about')} className="shrink-0 min-h-12 text-[#99D5D9] font-semibold">Mengenai kami →</button></section>
 </div>;
}
