import ProjectGallery from '../components/ProjectGallery';
import { useEffect } from 'react';
import { PageType } from '../types';
import { MANUFACTURER_CASES } from '../data/tasblockData';
import { presentationProjects } from '../data/presentationProjects';
import { asset } from '../components/PresentationMedia';
export default function ProjectsPage({onNavigate}:{onNavigate:(page:PageType)=>void}) {
 const projects = [
 ...presentationProjects.map(p=>({id:p.id,title:p.title,description:p.description+(p.id==='seaplast-2023'?' Pengeluar melaporkan pembinaan dalam 1 hari oleh 2 pekerja menggunakan komponen guna semula.':''),images:p.images.map(id=>asset(id).url),facts:[p.location,p.year]})),
 ...MANUFACTURER_CASES.map(p=>({id:p.id,title:p.title,description:p.description+' '+p.caveat+(p.id==='schools-2017'?' Kajian bilik darjah 9 m × 7.5 m turut membandingkan struktur, tenaga kerja, berat bahan, logistik dan sisa.':''),images:p.id==='schools-2017'?[p.image.src,...[100,101,102,103,104,105,106,107,108,109,110].map(n=>`/images/tasblock/school-${n}.jpeg`)]:p.id==='istanbul-office'?['/images/tasblock/source-132.jpeg',p.image.src]:p.id==='baghdad-warehouse'?['/images/tasblock/source-134.jpeg','/images/tasblock/source-133.jpeg',p.image.src]:p.id==='felda-hostel'?[p.image.src,...['felda-hostel-wall-assembly-01','felda-hostel-wall-assembly-02','felda-hostel-component-delivery'].map(id=>asset(id).url)]:p.id==='demo-2016'?[p.image.src,asset('tasblock-show-house-2016-exterior').url]:[p.image.src],facts:['istanbul-office','baghdad-warehouse'].includes(p.id)?[...p.facts,'Projek rakan kerjasama · 2011']:p.facts})),
 {id:'lktn',title:'Rumah IBS LKTN',description:'Pemasangan lengkap dilaporkan dalam 3 hari dalam kajian kes pengeluar. Tempoh ini merujuk skop pemasangan kes tersebut.',images:['/images/tasblock/project-lktn.jpeg'],facts:['Rumah IBS','3 hari pemasangan']},
 {id:'icw',title:'Struktur kecil ICW 2017',description:'Satu hentian bas dan satu pergola di CIDB Convention Centre, dengan tempoh binaan dilaporkan 4 jam bagi setiap struktur.',images:['/images/tasblock/project-icw.jpeg'],facts:['2017','4 jam setiap struktur']},
 {id:'dtact',title:'D-TACT',description:'Konsep struktur mudah alih prasiap volumetrik untuk kemudahan pengesanan penyakit berjangkit.',images:['/images/tasblock/project-dtact.jpeg'],facts:['Struktur mudah alih']},
 ];
 useEffect(()=>{const id=new URLSearchParams(window.location.hash.split('?')[1]).get('project');if(id) requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView({block:'start'}));},[]);
 return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8"><header className="max-w-3xl space-y-4"><p className="text-sm text-[#99D5D9]">PROJEK & APLIKASI</p><h1 className="text-3xl sm:text-5xl font-bold text-white">Tasblock di tapak sebenar</h1><p className="text-slate-300">Rujukan projek Tasblock (M) Sdn. Bhd. Setiap projek dipaparkan sekali, bersama foto dan butiran kes. Rekod ini ialah pengalaman pengeluar.</p></header><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 items-stretch">{projects.map(p=><article id={p.id} key={p.id} className="scroll-mt-36 min-w-0 h-full flex flex-col rounded-2xl overflow-hidden border border-slate-700 bg-slate-900/50"><ProjectGallery images={p.images} title={p.title}/><div className="p-5 flex flex-1 flex-col gap-4"><h2 className="text-lg leading-snug font-bold text-white md:min-h-[3.25rem]">{p.title}</h2><div className="flex flex-wrap gap-2">{p.facts.map(f=><span key={f} className="text-xs rounded-full bg-[#12314a] px-3 py-1 text-[#99D5D9]">{f}</span>)}</div><p className="text-sm text-slate-300 leading-relaxed">{p.description}</p></div></article>)}</div><button onClick={()=>onNavigate('enquiry')} className="rounded-xl bg-[#99D5D9] text-[#071827] font-bold px-6 py-3">Bincangkan projek anda →</button></div>;
}
