import { COMPANY_CONTACT } from '../data/tasblockData';
import { SectionLabel } from './PageContents';
const families = [
 {title:'Panel Dinding',image:86,codes:'W12 (A) · W3 (A) · W2 (A) · WB (A)',text:'Panel komposit yang disusun bersama adaptor untuk membentuk dinding. Sambungan sistem diperkenalkan oleh pengeluar sebagai FlexiFit.',details:['W12: 1,200 mm; W3: 300 mm; W2: 200 mm','WB: panel rasuk dinding 300 mm','Tinggi panel 400 mm tanpa gigi; 500 mm termasuk gigi','Unit bekalan panel: set']},
 {title:'Adaptor Tapak',image:84,codes:'B1 · B2 · B3 · B6 · BC',text:'Komponen pada dasar susunan dinding. Pilihan lurus dan sudut diselaraskan dengan pelan panel serta titik permulaan pemasangan.',details:['Pilihan lurus: 100, 200, 300 dan 600 mm','Sudut BC: 200 × 400 mm atau 300 × 300 mm','Tinggi adaptor tapak: 50 mm','Unit bekalan: keping']},
 {title:'Adaptor Dinding',image:84,codes:'A1 · A2 · A3 · A12 · AC',text:'Adaptor melengkapkan susunan lapisan panel dan sambungan sudut dalam sistem dinding.',details:['Pilihan lurus: 100, 200, 300 dan 1,200 mm','Sudut AC: 200 × 400 mm','Tinggi adaptor dinding: 100 mm','Unit bekalan: keping']},
 {title:'Rasuk',image:82,codes:'Be1 · Be2',text:'Keluarga rasuk yang dinamakan dalam katalog pengeluar, melengkapkan rangkaian dinding dan lantai.',details:['Dipilih mengikut bentangan, sokongan dan reka bentuk struktur','Profil serta dimensi khusus perlu dipadankan dengan spesifikasi projek']},
 {title:'Aksesori & Penyambung',image:85,codes:'Komponen sambungan sistem',text:'Aksesori melengkapkan sambungan antara komponen utama. Rajah menunjukkan contoh susunan komponen dalam rangkaian pengeluar.',details:['Jenis penyambung bergantung pada komponen yang dipadankan','Rujuk butiran sambungan projek untuk kod dan kuantiti yang tepat']},
 {title:'Komponen Lantai',image:83,codes:'Waffle slabs · Folded-plate floors',text:'Komponen lantai komposit melengkapkan sistem binaan bersama dinding dan rasuk.',details:['Pilihan sistem lantai mengikut bentangan dan beban reka bentuk','Susunan panel, sokongan dan sambungan perlu dirujuk kepada pelan struktur']},
];
export default function ComponentCatalogue(){return <section id="components" tabIndex={-1} className="scroll-mt-36 space-y-6"><SectionLabel id="components"/><h2 className="text-2xl sm:text-3xl font-bold text-white">Kenali komponen & fungsinya</h2><p className="max-w-3xl text-slate-300">Keluarga komponen daripada pengeluar, dengan pilihan saiz daripada senarai produk dan maklumat ketinggian komponen.</p><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{families.map(p=><article key={p.title} className="overflow-hidden rounded-2xl border border-slate-700 bg-slate-900/60 flex flex-col"><div className="bg-white p-4"><img src={`/images/tasblock/component-${p.image}.png`} alt={`Ilustrasi keluarga komponen: ${p.title}`} className="w-full h-44 object-contain" loading="lazy"/></div><div className="p-5 flex flex-col gap-4 flex-1"><h3 className="text-xl font-bold text-white">{p.title}</h3><p className="text-sm font-mono text-[#99D5D9]">{p.codes}</p><p className="text-sm text-slate-300 leading-relaxed">{p.text}</p><ul className="list-disc pl-4 space-y-2 text-sm text-slate-300">{p.details.map(d=><li key={d}>{d}</li>)}</ul><a className="mt-auto pt-3 text-sm font-bold text-[#99D5D9]" href={`${COMPANY_CONTACT.whatsappBaseUrl}?text=${encodeURIComponent('Salam, saya ingin spesifikasi '+p.title)}`} target="_blank" rel="noopener noreferrer">Tanya tentang komponen →</a></div></article>)}</div><p className="text-xs text-slate-400">Dimensi dalam mm.</p></section>}
