import EmbeddedVideo from './EmbeddedVideo';
import { SectionLabel } from './PageContents';
import CompressionTest from './CompressionTest';
function EvidencePhoto({file,alt}:{file:string;alt:string}) {
 return <figure className="space-y-2"><a href={`/images/tasblock/${file}`} target="_blank" rel="noopener noreferrer" aria-label={`${alt} — buka imej penuh`}><img src={`/images/tasblock/${file}`} alt={alt} loading="lazy" className="w-full aspect-[4/3] object-cover rounded-xl"/></a><figcaption className="text-xs text-slate-400">{alt}</figcaption></figure>;
}
export default function TechnicalEvidence() {
 return <section id="technical" tabIndex={-1} className="scroll-mt-36 space-y-8" aria-labelledby="technical-title"><SectionLabel id="technical"/>
  <div className="space-y-3 max-w-3xl"><h2 id="technical-title" className="text-2xl sm:text-3xl font-bold text-white">Prestasi bahan & aplikasi sebenar</h2><p className="text-slate-300">Kenali ujian bahan, demonstrasi dan contoh penggunaan melalui imej serta maklumat Tasblock (M) Sdn. Bhd.</p></div>
  <CompressionTest/>
  <article className="grid lg:grid-cols-2 gap-6 rounded-2xl border border-slate-700 p-5 sm:p-8"><div className="space-y-4"><h3 className="text-xl font-bold text-white">Kemasan & pemasangan penambat</h3><p className="text-slate-300 leading-relaxed">Sistem plaster nipis digunakan bersama lapisan agen pengikat. Pengeluar turut menunjukkan aplikasi penambat untuk peralatan mekanikal dan elektrikal serta kelengkapan yang digantung pada dinding.</p><ul className="list-disc pl-5 space-y-2 text-slate-300"><li>Demonstrasi lekatan plaster pada panel.</li><li>Ujian tarik keluar dan ricih penambat diterangkan oleh pengeluar.</li><li>Jenis skru, penambat dan beban pemasangan perlu dipadankan dengan spesifikasi komponen.</li></ul></div><div className="space-y-4"><EvidencePhoto file="technical-plaster-demonstration.png" alt="Demonstrasi pada panel berkemasan plaster"/></div></article>
  <article className="rounded-2xl border border-slate-700 p-5 sm:p-8 space-y-5"><h3 className="text-xl font-bold text-white">Penambat: tarik keluar & aplikasi ricih</h3><p className="text-slate-300">Pengeluar merujuk ASTM E488–2010 dan menunjukkan dua aplikasi pemasangan. Angka di bawah disalin sebagaimana dilaporkan, bukan beban kerja selamat yang boleh terus digunakan untuk pemasangan.</p><div className="grid sm:grid-cols-2 gap-5"><div className="space-y-3"><EvidencePhoto file="technical-ceiling-anchor.jpeg" alt="Peralatan mekanikal dan elektrikal digantung pada papak"/><p className="font-bold text-[#99D5D9]">251.3 kg — tarik keluar pengikat</p><p className="text-sm text-slate-300">Dilaporkan menggunakan skru kepingan logam.</p></div><div className="space-y-3"><EvidencePhoto file="technical-wall-mounted-fixture.jpeg" alt="Kelengkapan digantung pada dinding"/><p className="font-bold text-[#99D5D9]">360.6 kg — nilai pengikat yang dilaporkan</p><p className="text-sm text-slate-300">Sumber meletakkan nilai ini pada bahagian aplikasi ricih tetapi melabelkannya “fastener pull-out”. Jenis keputusan perlu disahkan melalui laporan asal.</p></div></div></article>
  <article className="rounded-2xl border border-slate-700 p-5 sm:p-8 space-y-5"><h3 className="text-xl font-bold text-white">Lihat demonstrasi impak bahan</h3><p className="text-slate-300">Tiga rakaman asal menunjukkan hentaman pada bata tanah liat, bata simen dan panel Tasblock. Rakaman demonstrasi ini membantu melihat tindak balas bahan; ia bukan perbandingan makmal dengan keadaan ujian seragam.</p><div className="grid md:grid-cols-3 gap-5"><EmbeddedVideo file="impact-clay-brick.mp4" poster="/images/tasblock/impact-clay-brick-poster.jpg" title="Demonstrasi bata tanah liat"/><EmbeddedVideo file="impact-cement-brick.mp4" poster="/images/tasblock/impact-cement-brick-poster.jpg" title="Demonstrasi bata simen"/><EmbeddedVideo file="impact-tasblock.mp4" poster="/images/tasblock/impact-tasblock-poster.jpg" title="Demonstrasi panel Tasblock"/></div></article>
  <article className="grid md:grid-cols-[220px_minmax(0,1fr)] items-center gap-6 rounded-2xl border border-slate-700 p-5 sm:p-8"><EmbeddedVideo file="fire-demonstration.mp4" poster="/images/tasblock/fire-demonstration-poster.jpg" title="Rakaman demonstrasi api pada bio-komposit kenaf" portrait/><div className="space-y-4"><h3 className="text-xl font-bold text-white">Tindak balas bahan terhadap api</h3><p className="text-slate-300 leading-relaxed">Pengeluar menerangkan demonstrasi bio-komposit kenaf yang didedahkan kepada nyalaan terus selama 1 jam dan menyatakan nyalaan padam kira-kira 3 saat selepas pembakar dialihkan. Ujian tersebut dikaitkan dengan Agensi Nuklear Malaysia dalam bahan pengeluar.</p><p className="text-sm text-slate-400">Imej demonstrasi ini bukan pengesahan penarafan ketahanan api bagi keseluruhan dinding atau bangunan. Dokumen ujian yang berkaitan diperlukan untuk menentukan prestasi sistem bagi projek.</p></div></article>
  <article className="rounded-2xl border border-slate-700 p-5 sm:p-8 space-y-5"><div className="max-w-3xl space-y-3"><h3 className="text-xl font-bold text-white">Ujian banjir & beban kitaran</h3><p className="text-slate-300 leading-relaxed">Ujian struktur bersaiz sebenar dilaporkan dijalankan pada Mac 2023 di NAHRIM bersama UKM. Pengeluar menamakan ujian ini “test to destruction”, dengan tempoh 100 minit dan paras air 800 mm. Menurut sumber, struktur rumah kekal berdiri walaupun dinding hadapan dihanyutkan. Rakaman kedua menunjukkan pembongkaran selepas ujian; ia bukan rakaman rumah runtuh semasa ujian.</p></div><div className="grid sm:grid-cols-2 gap-5"><EmbeddedVideo file="wave-test.mp4" poster="/images/tasblock/wave-test-poster.jpg" title="Semasa ujian ombak dan beban kitaran"/><EmbeddedVideo file="post-test-dismantling.mp4" poster="/images/tasblock/post-test-dismantling-poster.jpg" title="Pembongkaran selepas ujian"/></div><div className="grid sm:grid-cols-2 gap-5"><EvidencePhoto file="technical-flood-test.jpeg" alt="Sebelum ujian"/><EvidencePhoto file="technical-flood-after.jpeg" alt="Selepas ujian — keadaan struktur dalam rekod pengeluar"/></div></article>
  <div className="grid lg:grid-cols-2 gap-6"><article className="rounded-2xl border border-slate-700 p-5 sm:p-8 space-y-4"><EvidencePhoto file="technical-floating-jetty.jpeg" alt="Jeti terapung di Tanjong Kapor, Semporna"/><h3 className="text-xl font-bold text-white">Aplikasi luar & persekitaran air</h3><p className="text-slate-300 leading-relaxed">Jeti terapung Tanjong Kapor di Semporna ialah contoh aplikasi tahun 2018 dalam rekod pengeluar. Bahan komposit diperkenalkan untuk aplikasi seperti jeti terapung, rumah air dan dek luaran, mengikut reka bentuk serta spesifikasi bahan.</p></article><article className="rounded-2xl border border-slate-700 p-5 sm:p-8 space-y-4"><EvidencePhoto file="technical-component-transport.jpeg" alt="Komponen Tasblock dimuatkan ke dalam treler"/><h3 className="text-xl font-bold text-white">Pengendalian bahan & logistik</h3><p className="text-slate-300 leading-relaxed">Dalam contoh FELDA, satu treler 40 kaki membawa set komponen bagi satu asrama bersama blok tandas. Penyusunan komponen dan berat bahan membantu perancangan penghantaran, pengendalian tapak dan penggunaan semula.</p></article></div>

 </section>;
}
